//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.QuestERD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestERDEntities : DbContext
    {
        public QuestERDEntities()
            : base("name=QuestERDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerContacts> CustomerContacts { get; set; }
        public virtual DbSet<CustomerIndustrySegments> CustomerIndustrySegments { get; set; }
        public virtual DbSet<CustomerLocations> CustomerLocations { get; set; }
        public virtual DbSet<CustomerProductPrices> CustomerProductPrices { get; set; }
        public virtual DbSet<CustomerProducts> CustomerProducts { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<CustomerServicePrices> CustomerServicePrices { get; set; }
        public virtual DbSet<CustomerServices> CustomerServices { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<IndustrySegments> IndustrySegments { get; set; }
        public virtual DbSet<ProductPrices> ProductPrices { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ServiceEquipments> ServiceEquipments { get; set; }
        public virtual DbSet<ServiceEvents> ServiceEvents { get; set; }
        public virtual DbSet<ServicePrices> ServicePrices { get; set; }
        public virtual DbSet<ServiceRegionTypes> ServiceRegionTypes { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Vendors> Vendors { get; set; }
    }
}
