//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailRecipients
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public int RecipientId { get; set; }
        public int Retries { get; set; }
        public Nullable<System.DateTime> Sent { get; set; }
    }
}
