//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMessages
    {
        public int Id { get; set; }
        public int SenderId { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public System.DateTime Created { get; set; }
    }
}
