//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstantMessageRecipients
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public Nullable<int> ChatRoomId { get; set; }
        public int Retries { get; set; }
        public bool bUndeliverable { get; set; }
        public System.DateTime Received { get; set; }
    }
}
