//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstantMessageContacts
    {
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public int StateId { get; set; }
        public int NumMessages { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
    }
}
