//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMSEntities : DbContext
    {
        public FMSEntities()
            : base("name=FMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupPrivileges> GroupPrivileges { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<GroupUsers> GroupUsers { get; set; }
        public virtual DbSet<Privileges> Privileges { get; set; }
        public virtual DbSet<UserPrivileges> UserPrivileges { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSessionPrivileges> UserSessionPrivileges { get; set; }
        public virtual DbSet<UserSessions> UserSessions { get; set; }
        public virtual DbSet<EmailFolders> EmailFolders { get; set; }
        public virtual DbSet<EmailMessageAttachments> EmailMessageAttachments { get; set; }
        public virtual DbSet<EmailMessages> EmailMessages { get; set; }
        public virtual DbSet<EmailRecipients> EmailRecipients { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<ProfileEventCategories> ProfileEventCategories { get; set; }
        public virtual DbSet<ProfileEvents> ProfileEvents { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Timezones> Timezones { get; set; }
        public virtual DbSet<USStates> USStates { get; set; }
        public virtual DbSet<ZipCodes> ZipCodes { get; set; }
        public virtual DbSet<Zones> Zones { get; set; }
        public virtual DbSet<ChatRooms> ChatRooms { get; set; }
        public virtual DbSet<ChatRoomUsers> ChatRoomUsers { get; set; }
        public virtual DbSet<InstantMessageAttachments> InstantMessageAttachments { get; set; }
        public virtual DbSet<InstantMessageContacts> InstantMessageContacts { get; set; }
        public virtual DbSet<InstantMessageContactStates> InstantMessageContactStates { get; set; }
        public virtual DbSet<InstantMessageFolders> InstantMessageFolders { get; set; }
        public virtual DbSet<InstantMessageRecipients> InstantMessageRecipients { get; set; }
        public virtual DbSet<InstantMessages> InstantMessages { get; set; }
        public virtual DbSet<InstantMessageStates> InstantMessageStates { get; set; }
        public virtual DbSet<ProfileEventConfigurations> ProfileEventConfigurations { get; set; }
        public virtual DbSet<vwInstantMessageContactsList2> vwInstantMessageContactsList2 { get; set; }
        public virtual DbSet<vwInstantMessageThreadList> vwInstantMessageThreadList { get; set; }
        public virtual DbSet<vwLanguagesList> vwLanguagesList { get; set; }
        public virtual DbSet<vwTimezoneList> vwTimezoneList { get; set; }
    }
}
