//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSessions
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public System.DateTime LastAction { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<bool> bLoggedOut { get; set; }
        public Nullable<bool> bTimedOut { get; set; }
        public Nullable<System.DateTime> Terminated { get; set; }
    }
}
