//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCodes
    {
        public int Id { get; set; }
        public string zip { get; set; }
        public string type { get; set; }
        public bool decommissioned { get; set; }
        public string primary_city { get; set; }
        public string acceptable_cities { get; set; }
        public string unacceptable_cities { get; set; }
        public string state { get; set; }
        public string county { get; set; }
        public string timezone { get; set; }
        public string area_codes { get; set; }
        public string world_region { get; set; }
        public string country { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public int estimated_population_2013 { get; set; }
    }
}
