//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.MasterPricing
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterItemJoins
    {
        public int Id { get; set; }
        public int FilterItemId { get; set; }
        public string JoinType { get; set; }
        public string SourceSchema { get; set; }
        public string SourceEntityName { get; set; }
        public string SourceColumnName { get; set; }
        public int TargetEntityTypeId { get; set; }
        public string TargetSchema { get; set; }
        public string TargetEntityName { get; set; }
        public string TargetColumnName { get; set; }
    }
}
