//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.MasterPricing
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSettings
    {
        public int Id { get; set; }
        public bool bLogHTTPRequests { get; set; }
        public bool bLogExceptions { get; set; }
        public bool bLogStoredProcedures { get; set; }
        public bool bLogDatabases { get; set; }
        public bool bLogTablesets { get; set; }
        public bool bLogFilters { get; set; }
        public bool bLogBulkInserts { get; set; }
        public bool bLogBulkInsertsPerRow { get; set; }
        public bool bLogBulkUpdates { get; set; }
        public bool bLogBulkUpdatesPerRow { get; set; }
        public bool bLogPortal { get; set; }
        public bool bAllowLogUsers { get; set; }
        public System.DateTime LastModified { get; set; }
    }
}
