//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.MasterPricing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPricingEntities : DbContext
    {
        public MasterPricingEntities()
            : base("name=MasterPricingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FilterColumns> FilterColumns { get; set; }
        public virtual DbSet<FilterEntityTypes> FilterEntityTypes { get; set; }
        public virtual DbSet<FilterFolders> FilterFolders { get; set; }
        public virtual DbSet<FilterItemJoins> FilterItemJoins { get; set; }
        public virtual DbSet<FilterItems> FilterItems { get; set; }
        public virtual DbSet<FilterOperations> FilterOperations { get; set; }
        public virtual DbSet<FilterOperators> FilterOperators { get; set; }
        public virtual DbSet<FilterProcedureParameters> FilterProcedureParameters { get; set; }
        public virtual DbSet<FilterProcedures> FilterProcedures { get; set; }
        public virtual DbSet<Filters> Filters { get; set; }
        public virtual DbSet<FilterTables> FilterTables { get; set; }
        public virtual DbSet<FilterValues> FilterValues { get; set; }
        public virtual DbSet<FilterViews> FilterViews { get; set; }
        public virtual DbSet<Columns> Columns { get; set; }
        public virtual DbSet<Databases> Databases { get; set; }
        public virtual DbSet<EntityTypes> EntityTypes { get; set; }
        public virtual DbSet<Lookups> Lookups { get; set; }
        public virtual DbSet<StoredProcedureParameters> StoredProcedureParameters { get; set; }
        public virtual DbSet<StoredProcedures> StoredProcedures { get; set; }
        public virtual DbSet<Tables> Tables { get; set; }
        public virtual DbSet<TypeLists> TypeLists { get; set; }
        public virtual DbSet<Views> Views { get; set; }
        public virtual DbSet<TablesetColumns> TablesetColumns { get; set; }
        public virtual DbSet<Tablesets> Tablesets { get; set; }
        public virtual DbSet<TablesetTables> TablesetTables { get; set; }
        public virtual DbSet<TablesetViews> TablesetViews { get; set; }
        public virtual DbSet<vwLookupsList4> vwLookupsList4 { get; set; }
        public virtual DbSet<vwTablesetsList4> vwTablesetsList4 { get; set; }
        public virtual DbSet<vwTablesetTablesList2> vwTablesetTablesList2 { get; set; }
        public virtual DbSet<vwTablesetViewsList2> vwTablesetViewsList2 { get; set; }
        public virtual DbSet<vwTypeListsList> vwTypeListsList { get; set; }
    }
}
