//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.MasterPricing
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredProcedureParameters
    {
        public int Id { get; set; }
        public int StoredProcedureId { get; set; }
        public bool bRequired { get; set; }
        public int Offset { get; set; }
        public string ParameterName { get; set; }
        public string DbType { get; set; }
        public string Direction { get; set; }
        public string SqlDbType { get; set; }
        public int Size { get; set; }
        public bool IsNullable { get; set; }
        public Nullable<bool> ForceColumnEncryption { get; set; }
        public Nullable<int> LocaleId { get; set; }
        public byte[] Precision { get; set; }
        public byte[] Scale { get; set; }
        public string SourceColumn { get; set; }
        public Nullable<bool> SourceColumnNullMapping { get; set; }
        public string TypeName { get; set; }
        public string UdtTypeName { get; set; }
    }
}
