//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quest.Services.Dbio.MasterPricing
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLookupsList4
    {
        public int Id { get; set; }
        public int DatabaseId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public string Summary { get; set; }
        public string SQL { get; set; }
        public string KeyField { get; set; }
        public string TextFields { get; set; }
        public string Arguments { get; set; }
        public string Database { get; set; }
    }
}
